# Generated by Django 5.2 on 2025-08-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='profile_pictures/%Y:%m:%d'),
        ),
    ]
